name: Build Reader

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild (VS2019)
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '[16.0,17.0)'  # prefer VS2019 (v142 toolset)

      - name: Build (Release x86)
        run: msbuild Reader.sln /p:Configuration=Release /p:Platform=x86 /p:PlatformToolset=v142

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Reader-x86-Release
          path: Release/Reader.exe

      - name: Build (Release x64)
        run: msbuild Reader.sln /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v142

      - name: Upload x64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: Reader-x64-Release
          path: x64/Release/Reader.exe
